#spring:
#  liquibase:
#    change-log: classpath:db/changelog/master.xml
#  datasource:
#    url: jdbc:h2:mem:test;DATABASE_TO_LOWER=true

#  h2:
#    console:
#      path: /h2
#
#  jpa:
#    open-in-view: false
#    show-sql: true


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/device_rent?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Europe/Warsaw
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin

  jpa:
    #   wyświetlanie wykonywanych przez hibernate zapytań do bazy danych
    show-sql: true
    #   automatyczne generowanie schematu bazy
    generate-ddl: true
    open-in-view: false