spring:
  datasource:
    url: jdbc:mysql://localhost:3306/device_rent?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Europe/Warsaw
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin

  jpa:
    show-sql: true

  liquibase:
    contexts: prod