spring:
  datasource:
    url: jdbc:mysql://localhost:3306/device_rent?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Europe/Warsaw
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin

  jpa:
    #   wyświetlanie wykonywanych przez hibernate zapytań do bazy danych
    show-sql: true
    #   automatyczne generowanie schematu bazy
    generate-ddl: true
    open-in-view: false