spring:
  datasource:
    url: jdbc:h2:mem:test;DATABASE_TO_LOWER=true

  h2:
    console:
      path: /h2
      enabled: true

# Ustawienie, aby h2 sie uruchomila https://www:baeldung:com/spring-boot-h2-database#2-hibernate-and-datasql:
  jpa:
    defer-datasource-initialization: true
    open-in-view: true
